---
hard_drive:
  mount_point: /media/usbdrive
  mount_src: UUID=3db34317-0803-33c1-bc6e-95a49b7f56fd
  music_path: /media/music
  video_path: /media/video

minidlna:
  db_dir: /home/minidlna/.minidlnadb
  log_dir: /home/minidlna
